### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by SnubSum31041247** [moran0710/MinecraftServer_BaiduNetdisk_backup#4]
[MCDR] [22:11:36] [TaskExecutor/ERROR]: Fail to load the entry point of baidu_netdisk_backup@1.0.0
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 88, in _on_ready
    self._load_entry_instance()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\plugin\type\regular_plugin.py", line 66, in _load_entry_instance
    self.entry_module_instance = self._import_entrypoint_module()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 56, in _import_entrypoint_module
    mod = importlib.import_module(self.get_metadata().entrypoint)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "plugins\baidu_netdisk_backup_v_1_0_1.mcdr\baidu_netdisk_backup\__init__.py", line 9, in <module>
    from . import upload
  File "<frozen zipimport>", line 259, in load_module
  File "plugins\baidu_netdisk_backup_v_1_0_1.mcdr\baidu_netdisk_backup\upload.py", line 7, in <module>
    from .utils import get_config, get_server
  File "<frozen zipimport>", line 259, in load_module
  File "plugins\baidu_netdisk_backup_v_1_0_1.mcdr\baidu_netdisk_backup\utils.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by moran0710** [comment]
pip install pyyaml

**Comment by SnubSum31041247** [comment]
> pip install pyyaml

OK已解决

**Comment by moran0710** [comment]
ok close

**Comment by SnubSum31041247** [comment]
> ok close

> !!baidu_backup
[MCDR] [17:44:37] [TaskExecutor/INFO] [baidu_netdisk_backup]: 正在载入配置...
[Server] [17:44:37] [Server thread/INFO]: Stopping the server
[Server] [17:44:37] [Server thread/INFO]: Stopping server
[Server] [17:44:37] [Server thread/INFO]: Saving players
[Server] [17:44:37] [Server thread/INFO]: Saving worlds
[Server] [17:44:37] [Server thread/INFO]: Saving chunks for level 'ServerLevel[important]'/minecraft:overworld
[Server] [17:44:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[important]'/minecraft:the_end
[Server] [17:44:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[important]'/minecraft:the_nether
[Server] [17:44:38] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [17:44:38] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [17:44:38] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [17:44:38] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[MCDR] [17:44:47] [WatchDog/WARNING]: TaskExecutor 线程已经 10 秒没有响应了，可能出了些问题
[MCDR] [17:44:47] [WatchDog/WARNING]: 正在于 TaskExecutor 线程中运行的插件 (如果存在的话): baidu_netdisk_backup@1.0.0
[MCDR] [17:44:47] [WatchDog/WARNING]: 重建 TaskExecutor 中

怎么解决啊

**Comment by moran0710** [comment]
em

**Comment by moran0710** [comment]
我先试着复现一下，上传的时候没有出现这个问题

**Comment by moran0710** [comment]
em 你的服务器插件数量多不多，如果多的话，参照mcdr文档，将mcdr的config.yml watchdog_threshold调大试试（默认值为10）
我这里想办法写一个修复版本，知道缺陷在哪里了
因为要关服再备份，插件多的话，关服时间太长，会被mcdr的watchdog机制杀掉
当时写的时候暂时没有特别好的解决方法

**Comment by moran0710** [comment]
时间参考的话，比你正常关闭服务端所用的时间长10s差不多

**Comment by moran0710** [comment]
问题出在 我启动第二个线程的话就获取不到server，我查不到mcdr的文档

目前的解决方案是设置watchdog的时间长于你的服务器关闭所需的时间10s

我后面研究了（

**Comment by SnubSum31041247** [comment]
23个插件

**Comment by SnubSum31041247** [comment]
我试试

**Comment by SnubSum31041247** [comment]
> 问题出在 我启动第二个线程的话就获取不到server，我查不到mcdr的文档
> 
> 目前的解决方案是设置watchdog的时间长于你的服务器关闭所需的时间10s
> 
> 我后面研究了（

修改watchDog值之后
[MCDR] [19:23:08] [TaskExecutor/INFO] [baidu_netdisk_backup]:
[MCDR] [19:23:08] [TaskExecutor/INFO] [baidu_netdisk_backup]:           Baidu Netdisk Backup Plugin
[MCDR] [19:23:08] [TaskExecutor/INFO] [baidu_netdisk_backup]:               --Powered By ByPy & Moran0710
[MCDR] [19:23:08] [TaskExecutor/INFO] [baidu_netdisk_backup]:
[MCDR] [19:23:08] [TaskExecutor/INFO] [baidu_netdisk_backup]: 正在测试百度网盘登录状态..
[MCDR] [19:23:08] [TaskExecutor/INFO] [baidu_netdisk_backup]: 如果出现url，请登录
<E> [19:23:09] Waiting 10 seconds before retrying...
<E> [19:23:19] Request Try #2 / 5
[MCDR] [19:23:20] [WatchDog/WARNING]: TaskExecutor 线程已经 12 秒没有响应了，可能出了些问题
[MCDR] [19:24:10] [WatchDog/WARNING]: 正在于 TaskExecutor 线程中运行的插件 (如果存在的话): baidu_netdisk_backup@1.0.0
[MCDR] [19:24:10] [WatchDog/WARNING]: 重建 TaskExecutor 中
<E> [19:24:10] Waiting 20 seconds before retrying...
<E> [19:24:30] Request Try #3 / 5
<E> [19:24:30] Waiting 30 seconds before retrying...
<E> [19:25:00] Request Try #4 / 5
<E> [19:25:00] Waiting 40 seconds before retrying...
<E> [19:25:40] Request Try #5 / 5
<E> [19:25:40] Maximum number (5) of tries failed.
<E> [19:25:40] FATAL: Token refreshing failed, can't continue.
Quitting...

**Comment by moran0710** [comment]
这几天在学考，我放假后想办法修复

**Comment by moran0710** [comment]
暂时先不要使用吧（

**Comment by SnubSum31041247** [comment]
好的
